-- MAN's Crafts — catalogue and order schema.
-- Money is numeric(10,2) so prices never touch floating point.

do $$
begin
  if not exists (select 1 from pg_type where typname = 'order_status') then
    create type public.order_status as enum ('pending', 'confirmed', 'fulfilled', 'cancelled');
  end if;
end
$$;

-- Sequential, human-readable order numbers: MC-2026-00001
create sequence if not exists public.order_number_seq;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null,
  sku text not null,
  name text not null,
  category text not null,
  color text not null default '',
  description text not null default '',
  price numeric(10,2) not null,
  image_url text not null default '',
  stock integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_slug_key unique (slug),
  constraint products_sku_key unique (sku),
  constraint products_price_check check (price >= 0),
  constraint products_stock_check check (stock >= 0)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer_phone text,
  status public.order_status not null default 'pending',
  currency text not null default 'INR',
  subtotal numeric(10,2) not null default 0 check (subtotal >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders (id) on delete cascade,
  product_id bigint not null references public.products (id),
  quantity integer not null check (quantity > 0),
  -- unit_price snapshots the price at order time so later catalogue edits
  -- never rewrite the value of an order that has already been placed.
  unit_price numeric(10,2) not null check (unit_price >= 0),
  created_at timestamptz not null default now()
);

create index if not exists order_items_order_id_idx on public.order_items (order_id);

-- ---------------------------------------------------------------------------
-- Upgrade path for the earlier hand-made `products` table: it had no slug, sku,
-- stock, active or updated_at columns, its id had no default, and prices were
-- plain numeric. Everything below is a no-op on a freshly created database.
-- ---------------------------------------------------------------------------

alter table public.products add column if not exists slug text;
alter table public.products add column if not exists sku text;
alter table public.products add column if not exists stock integer not null default 0;
alter table public.products add column if not exists active boolean not null default true;
alter table public.products add column if not exists updated_at timestamptz not null default now();
alter table public.products alter column color set default '';
alter table public.products alter column description set default '';
alter table public.products alter column image_url set default '';

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'id' and is_identity = 'YES'
  ) then
    alter table public.products alter column id add generated by default as identity;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'products' and column_name = 'price'
      and (numeric_precision is distinct from 10 or numeric_scale is distinct from 2)
  ) then
    alter table public.products alter column price type numeric(10,2);
  end if;

  -- Tighten to NOT NULL only where the existing data already satisfies it.
  if not exists (select 1 from public.products where slug is null) then
    alter table public.products alter column slug set not null;
  end if;
  if not exists (select 1 from public.products where sku is null) then
    alter table public.products alter column sku set not null;
  end if;
  if not exists (select 1 from public.products where color is null) then
    alter table public.products alter column color set not null;
  end if;
  if not exists (select 1 from public.products where description is null) then
    alter table public.products alter column description set not null;
  end if;
  if not exists (select 1 from public.products where image_url is null) then
    alter table public.products alter column image_url set not null;
  end if;

  if not exists (select 1 from pg_constraint where conrelid = 'public.products'::regclass and conname = 'products_slug_key') then
    alter table public.products add constraint products_slug_key unique (slug);
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.products'::regclass and conname = 'products_sku_key') then
    alter table public.products add constraint products_sku_key unique (sku);
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.products'::regclass and conname = 'products_price_check') then
    alter table public.products add constraint products_price_check check (price >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.products'::regclass and conname = 'products_stock_check') then
    alter table public.products add constraint products_stock_check check (stock >= 0);
  end if;
end
$$;

-- Created after the convergence block, since `active` may only just have appeared.
create index if not exists products_active_idx on public.products (id) where active;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
  before update on public.products
  for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();
