-- P2: monitoring for failed checkouts.
--
-- When create_order fails, the storefront still hands the order to WhatsApp, so
-- the sale is not lost — but until now nothing recorded that it happened. These
-- rows sit next to the orders in the admin page, so a run of failures is
-- visible rather than silent.

create table if not exists public.order_failures (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  error_code text not null default '',
  error_message text not null default '' check (length(error_message) <= 500),
  client_order_id uuid,
  client_session_id text,
  client_ip text,
  item_count integer not null default 0 check (item_count >= 0),
  cart jsonb not null default '[]'::jsonb
);

create index if not exists order_failures_created_at_idx
  on public.order_failures (created_at desc);

alter table public.order_failures enable row level security;

-- Writes go through the function below, so the payload shape and size are
-- controlled server-side rather than by whatever the browser feels like sending.
drop policy if exists "Admins can read order failures" on public.order_failures;
create policy "Admins can read order failures"
  on public.order_failures for select to authenticated
  using (public.is_admin());

create or replace function public.log_order_failure(
  p_error_code text,
  p_error_message text,
  p_items jsonb default '[]'::jsonb,
  p_client_order_id uuid default null,
  p_client_session_id text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_headers text;
  v_client_ip text;
  v_id bigint;
  v_items jsonb;
begin
  -- jsonb_array_elements raises on anything that is not an array, so coerce the
  -- payload first rather than trusting the caller.
  v_items := case
    when jsonb_typeof(coalesce(p_items, '[]'::jsonb)) = 'array' then coalesce(p_items, '[]'::jsonb)
    else '[]'::jsonb
  end;

  v_headers := nullif(current_setting('request.headers', true), '');
  if v_headers is not null then
    begin
      v_client_ip := nullif(trim(split_part(coalesce(v_headers::jsonb ->> 'x-forwarded-for', ''), ',', 1)), '');
    exception when others then
      v_client_ip := null;
    end;
  end if;

  insert into public.order_failures (
    error_code, error_message, client_order_id, client_session_id, client_ip, item_count, cart
  )
  values (
    left(coalesce(p_error_code, ''), 20),
    left(coalesce(p_error_message, 'Unknown error'), 500),
    p_client_order_id,
    left(coalesce(p_client_session_id, ''), 64),
    left(coalesce(v_client_ip, ''), 64),
    jsonb_array_length(v_items),
    -- Only product ids and quantities: never anything the customer typed.
    coalesce(
      (select jsonb_agg(jsonb_build_object('product_id', e ->> 'product_id', 'quantity', e ->> 'quantity'))
         from jsonb_array_elements(v_items) e),
      '[]'::jsonb
    )
  )
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.log_order_failure(text, text, jsonb, uuid, text) from public;
grant execute on function public.log_order_failure(text, text, jsonb, uuid, text) to anon, authenticated;
